BEGIN;

CREATE TABLE IF NOT EXISTS kanthorq_stream (
  topic VARCHAR(128) NOT NULL,
  event_id VARCHAR(64) NOT NULL,
  created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000,
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (topic, event_id)
);
CREATE INDEX idx_event_id ON kanthorq_stream USING HASH(event_id);

CREATE TABLE IF NOT EXISTS kanthorq_consumer (
  name VARCHAR(128) NOT NULL,
  topic VARCHAR(128) NOT NULL,
  cursor VARCHAR(64) NOT NULL,
  created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000,
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (name)
);

COMMIT;