version: "3.8"

services:
  storage:
    container_name: kanthorq-storage
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - $PWD/data:/kanthorlabs/kanthorq/data
    user: postgres
    command: >
      postgres 
      -c log_statement='all' 
      -c log_duration=on 
      -c log_min_duration_statement=0
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 8s
      timeout: 4s
      retries: 16

  pgbouncer:
    image: edoburu/pgbouncer
    depends_on:
      - storage
    container_name: kanthorq-pgbouncer
    restart: unless-stopped
    ports:
      - "6432:6432"
    networks:
      - kanthor
    environment:
      AUTH_TYPE: scram-sha-256
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_HOST: storage
      DB_NAME: $POSTGRES_USER
      POOL_MODE: transaction
      LISTEN_PORT: 6432
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      MIN_POOL_SIZE: 1
      MAX_DB_CONNECTIONS: 20
      MAX_USER_CONNECTIONS: 20
      SERVER_LIFETIME: 60
      SERVER_IDLE_TIMEOUT: 30
    healthcheck:
      test: ["CMD", "pgbouncer", "-R", "/etc/pgbouncer/pgbouncer.ini"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  kanthor:
    name: kanthorq