version: "3.8"

services:
  storage:
    container_name: kanthorq-storage
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - kanthor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$TEST_CONTAINER_POSTGRES_USER
      - POSTGRES_PASSWORD=$TEST_CONTAINER_POSTGRES_PASSWORD
    volumes:
      - $PWD/data:/kanthorlabs/kanthorq/data
    user: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 8s
      timeout: 4s
      retries: 16

networks:
  kanthor:
    name: kanthorq