receivers:
  postgresql:
    endpoint: storage:5432
    transport: tcp
    username: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    collection_interval: 5s
    connection_pool:
      max_idle_time: 5m
      max_lifetime: 30m
      max_idle: 0
      max_open: 2
    tls:
      insecure: true

exporters:
  file/metrics:
    path: /opentelemetry/metrics.log
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [postgresql]
      processors: [batch]
      exporters: [file/metrics, prometheus]